GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/61fda1c88e898042451a284c

###

GET http://localhost:3000/subscribers/name/Wiktor

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Wiktor",
    "subscribedToChannel": "Web Dev Simplified"
}

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": ""
}

###

DELETE http://localhost:3000/subscribers/61fda1c88e898042451a284c